export { default as About } from "./About/About";
export { default as Blog } from "./Blog/Blog";
export { default as Contact } from "./Contact/Contact";
export { default as Home } from "./Home/Home";
export { default as Portfolio } from "./Portfolio/Portfolio";
export { default as Blockchain } from "./Services/Blockchain/Blockchain";
export { default as Cloud } from "./Services/Cloud/Cloud";
export { default as Game } from "./Services/Game/Game";
export { default as WebAndMobile } from "./Services/Web and Mobile/WebAndMobile";
// export { default as Header } from "./Home/Header";
